# Generated by Django 2.1.4 on 2018-12-09 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Посты',
                'verbose_name_plural': 'Посты',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_user_id', models.ForeignKey(on_delete=None, related_name='subscription_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписки на ленты',
                'verbose_name_plural': 'Подписки на ленты',
            },
        ),
    ]
