# Generated by Django 2.1.4 on 2018-12-09 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_news_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 9, 14, 10, 43, 383656)),
        ),
    ]
