# Generated by Django 2.1.4 on 2018-12-10 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Прочитанные новости',
                'verbose_name_plural': 'Прочитанные новости',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 10, 9, 3, 45, 418623)),
        ),
        migrations.AlterField(
            model_name='news',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='read',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.News'),
        ),
        migrations.AddField(
            model_name='read',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
